### ISSUE TITLE
Support for all variants of Etherscan (PolygonScan, Optimism, Arbiscan, Basescan etc)

### ISSUE THREAD

**Issue by nnnnicholas** [dethcrypto/dethcode#78]
Would love to get back to using deth's VSCode shortcut with all the new block explorers I find myself looking at.

**Comment by krzkaczor** [comment]
Deth Code already supports multiple etherscan instances. Full list is here: https://github.com/dethcrypto/dethcode/blob/main/packages/ethereum-viewer/src/explorer/networks.ts#L69

Let me know which networks are lacking (I am just fixing support for optimism).
