### ISSUE TITLE
Feature Request: Add Support for FraxScan

### ISSUE THREAD

**Issue by tom2o17** [dethcrypto/dethcode#91]
Hey all long time user of dethcode here,

I was hoping it would be possible to add support for Fraxtal, a newly launched L2 based on the OP stack by Frax Finance.

https://fraxscan.com/

Fraxscan is an etherscan clone and any etherscan specific api calls should also abstract to fraxscan. 

lmk if there is anything I can do to help support this effort. 

 🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by krzkaczor** [comment]
@tom2o17 Thanks for the issue, it works now: https://fraxscan.deth.net/address/0x4200000000000000000000000000000000000015
